import type { Payment, Rail } from "./types";

export const payments: Payment[] = [
  {
    id: "AB-8F31A2",
    intent: "Vendor inventory settlement",
    rail: "M-Pesa",
    corridor: "KE · KES",
    amount: "KES 84,500",
    amountUsd: 655.27,
    recipient: "vendor_•••_7B2",
    status: "Awaiting approval",
    age: "38s",
    risk: "Moderate",
    reason: "Destructive tool · OAuth confirmation required",
  },
  {
    id: "AB-40C9E1",
    intent: "Field team weekly disbursement",
    rail: "MTN MoMo",
    corridor: "GH · GHS",
    amount: "GHS 12,800",
    amountUsd: 821.43,
    recipient: "wallet_•••_1D9",
    status: "Awaiting approval",
    age: "2m",
    risk: "High",
    reason: "Amount variance · enhanced review",
  },
  {
    id: "AB-DC108A",
    intent: "Customer checkout collection",
    rail: "Paystack",
    corridor: "NG · NGN",
    amount: "NGN 468,000",
    amountUsd: 298.14,
    recipient: "payer_•••_A04",
    status: "Reconciling",
    age: "4m",
    risk: "Low",
  },
  {
    id: "AB-558D21",
    intent: "Produce cooperative payout",
    rail: "M-Pesa",
    corridor: "KE · KES",
    amount: "KES 42,000",
    amountUsd: 325.68,
    recipient: "member_•••_904",
    status: "Confirmed",
    age: "11m",
    risk: "Low",
  },
  {
    id: "AB-7A61F4",
    intent: "Airtime partner settlement",
    rail: "Paystack",
    corridor: "NG · NGN",
    amount: "NGN 920,000",
    amountUsd: 586.08,
    recipient: "partner_•••_33C",
    status: "Budget stopped",
    age: "19m",
    risk: "Moderate",
  },
];

export const rails: Rail[] = [
  {
    name: "M-Pesa / Daraja",
    market: "Kenya · KES",
    status: "Operational",
    uptime: "99.98%",
    latency: "612 ms",
    color: "#26c281",
    bars: [46, 63, 58, 71, 67, 76, 72, 84, 78, 88, 82, 91],
  },
  {
    name: "Paystack",
    market: "Nigeria · NGN",
    status: "Operational",
    uptime: "99.95%",
    latency: "488 ms",
    color: "#4f8cff",
    bars: [59, 56, 68, 64, 73, 70, 80, 76, 75, 84, 81, 87],
  },
  {
    name: "MTN MoMo",
    market: "Ghana · GHS",
    status: "Degraded",
    uptime: "98.71%",
    latency: "1.8 s",
    color: "#f1b94a",
    bars: [78, 74, 70, 73, 61, 65, 55, 59, 48, 53, 42, 46],
  },
];

export const auditEvents = [
  { time: "10:42:18", title: "Confirmation challenge issued", detail: "AB-8F31A2 · OAuth · consent_•••_123", tone: "amber" },
  { time: "10:41:54", title: "Provider head confirmed payment", detail: "AB-558D21 · Daraja query · receipt verified", tone: "green" },
  { time: "10:40:07", title: "Callback evidence committed", detail: "AB-DC108A · event + FSM + outbox atomic", tone: "blue" },
  { time: "10:38:32", title: "HTTP 402 hard stop", detail: "AB-7A61F4 · OSCAL partial pack emitted", tone: "red" },
];
